const copy = {
  hy: {
    title: 'Գրանցման հարցում', intro: 'Ուղարկեք հարցում․ մենեջերի հաստատումից հետո կստեղծվի ձեր հաշիվը։',
    employee: 'Գրանցվել որպես ընկերության աշխատակից', client: 'Հաճախորդ', staff: 'Աշխատակից',
    name: 'Անուն', lastName: 'Ազգանուն', patronymic: 'Հայրանուն (ոչ պարտադիր)', email: 'Էլ․ փոստ',
    password: 'Գաղտնաբառ', confirmPassword: 'Հաստատեք գաղտնաբառը', passwordHint: 'Առնվազն 8 նիշ',
    jobTitle: 'Պաշտոնը', jobHint: 'Տեղեկատվության համար․ իրական հաստիքը նշանակում է մենեջերը։',
    company: 'Ընկերություն', selectCompany: 'Ընտրեք ընկերությունը', selectRole: 'Ընտրեք հաստիքը', selectFactory: 'Ընտրեք արտադրամասը',
    send: 'Ուղարկել հարցումը', sending: 'Ուղարկվում է…', accepted: 'Ձեր հարցումն ընդունված է։',
    acceptedHint: 'Հաշիվը կստեղծվի մենեջերի հաստատումից հետո։ Դրանից հետո կարող եք մուտք գործել ձեր նշած էլ․ փոստով և գաղտնաբառով։',
    login: 'Մուտք գործել', existing: 'Արդեն ունե՞ք հաշիվ։', sharedHint: 'Եթե արդեն ունեք հաշիվ այս հարթակում, օգտագործեք նույն էլ․ փոստն ու գործող գաղտնաբառը։',
    required: 'Լրացրեք այս դաշտը։', invalidEmail: 'Մուտքագրեք ճիշտ էլ․ փոստ։', shortPassword: 'Գաղտնաբառը պետք է լինի առնվազն 8 նիշ։', mismatch: 'Գաղտնաբառերը չեն համընկնում։',
    unavailable: 'Չհաջողվեց բեռնել ընկերությունները։', noCompanies: 'Գրանցման համար ակտիվ ընկերություն չկա։', retry: 'Կրկին փորձել', failed: 'Չհաջողվեց ուղարկել հարցումը։',
    requests: 'Գրանցման հարցումներ', reviewIntro: 'Ընտրված ընկերության աշխատակիցների և հաճախորդների հարցումները։',
    pending: 'Սպասում է հաստատման', approved: 'Հաստատված', rejected: 'Մերժված', allTypes: 'Բոլոր հարցումները', empty: 'Այս բաժնում հարցումներ չկան։', loading: 'Բեռնվում է…',
    approve: 'Հաստատել', reject: 'Մերժել', cancel: 'Չեղարկել', position: 'Հաստիք', workshop: 'Արտադրամաս',
    applicantJob: 'Նշված պաշտոնը', employeeReview: 'Ընտրեք իրական հաստիքը և անհրաժեշտության դեպքում արտադրամասը։',
    clientReview: 'Հաստատումից հետո կստեղծվի հաճախորդի հաշիվ։', permissionsHint: 'Աշխատակցի անհատական իրավունքները կառավարեք «Աշխատակիցների իրավունքներ» բաժնում։',
    rejectHint: 'Մերժված հարցումը հաշիվ չի ստեղծում։', reviewFailed: 'Չհաջողվեց մշակել հարցումը։', listFailed: 'Չհաջողվեց բեռնել հարցումները։', optionsFailed: 'Չհաջողվեց բեռնել հաստիքներն ու արտադրամասերը։',
    approvalSaved: 'Գրանցումը հաստատված է։',
    notification: { sent: 'Հաստատման նամակն ուղարկված է։', failed: 'Հաշիվը հաստատված է, բայց նամակի ուղարկումը չհաջողվեց։', unconfigured: 'Հաշիվը հաստատված է, բայց նամակների ուղարկումը սերվերում կարգավորված չէ։', pending: 'Հաստատման նամակը դեռ ուղարկված չէ։', sending: 'Նամակն ուղարկվում է…' },
    previous: 'Նախորդ', next: 'Հաջորդ', page: 'Էջ', rights: 'Իրավունքներ',
    roles: { admin: 'Ադմինիստրատոր', manager: 'Մենեջեր', engineer: 'Ինժիներ', laser: 'Լազերային կտրում', bend: 'Կռում', powder_catting: 'Փոշեներկում' },
  },
  ru: {
    title: 'Заявка на регистрацию', intro: 'Отправьте заявку. Менеджер подтвердит её и создаст ваш аккаунт.',
    employee: 'Зарегистрироваться как сотрудник компании', client: 'Клиент', staff: 'Сотрудник',
    name: 'Имя', lastName: 'Фамилия', patronymic: 'Отчество (необязательно)', email: 'Эл. почта',
    password: 'Пароль', confirmPassword: 'Подтвердите пароль', passwordHint: 'Не менее 8 символов',
    jobTitle: 'Должность', jobHint: 'Для информации. Рабочую должность назначит менеджер.',
    company: 'Предприятие', selectCompany: 'Выберите предприятие', selectRole: 'Выберите должность', selectFactory: 'Выберите цех',
    send: 'Отправить заявку', sending: 'Отправляем…', accepted: 'Ваша заявка принята.',
    acceptedHint: 'Аккаунт появится после подтверждения менеджером. Затем вы сможете войти с указанными почтой и паролем.',
    login: 'Войти', existing: 'Уже есть аккаунт?', sharedHint: 'Если у вас уже есть аккаунт на этой платформе, укажите ту же почту и действующий пароль.',
    required: 'Заполните это поле.', invalidEmail: 'Укажите правильный адрес почты.', shortPassword: 'Пароль должен содержать не менее 8 символов.', mismatch: 'Пароли не совпадают.',
    unavailable: 'Не удалось загрузить предприятия.', noCompanies: 'Сейчас нет предприятий, принимающих заявки.', retry: 'Повторить', failed: 'Не удалось отправить заявку.',
    requests: 'Заявки на регистрацию', reviewIntro: 'Заявки сотрудников и клиентов выбранного предприятия.',
    pending: 'Ожидают подтверждения', approved: 'Подтверждены', rejected: 'Отклонены', allTypes: 'Все заявки', empty: 'В этом разделе заявок нет.', loading: 'Загружаем…',
    approve: 'Подтвердить', reject: 'Отклонить', cancel: 'Отмена', position: 'Должность', workshop: 'Цех',
    applicantJob: 'Указанная должность', employeeReview: 'Назначьте рабочую должность и, если требуется, цех.',
    clientReview: 'После подтверждения появится аккаунт клиента.', permissionsHint: 'Индивидуальные права сотрудника назначаются в разделе «Права сотрудников».',
    rejectHint: 'Отклонение заявки не создаёт аккаунт.', reviewFailed: 'Не удалось обработать заявку.', listFailed: 'Не удалось загрузить заявки.', optionsFailed: 'Не удалось загрузить должности и цеха.',
    approvalSaved: 'Регистрация подтверждена.',
    notification: { sent: 'Письмо о подтверждении отправлено.', failed: 'Аккаунт подтверждён, но письмо не удалось отправить.', unconfigured: 'Аккаунт подтверждён, но отправка писем на сервере не настроена.', pending: 'Письмо о подтверждении ещё не отправлено.', sending: 'Письмо отправляется…' },
    previous: 'Назад', next: 'Далее', page: 'Страница', rights: 'Права доступа',
    roles: { admin: 'Администратор', manager: 'Менеджер', engineer: 'Инженер', laser: 'Лазерная резка', bend: 'Гибка', powder_catting: 'Порошковая покраска' },
  },
  en: {
    title: 'Registration request', intro: 'Send a request. Your account will be created after the manager approves it.',
    employee: 'Register as a company employee', client: 'Client', staff: 'Employee',
    name: 'First name', lastName: 'Last name', patronymic: 'Middle name (optional)', email: 'Email',
    password: 'Password', confirmPassword: 'Confirm password', passwordHint: 'At least 8 characters',
    jobTitle: 'Job title', jobHint: 'For information. The manager will assign your actual position.',
    company: 'Company', selectCompany: 'Select a company', selectRole: 'Select a position', selectFactory: 'Select a workshop',
    send: 'Send request', sending: 'Sending…', accepted: 'Your request has been accepted.',
    acceptedHint: 'Your account will be created after manager approval. You can then sign in with the email and password you provided.',
    login: 'Sign in', existing: 'Already have an account?', sharedHint: 'If you already have an account on this platform, use the same email and your current password.',
    required: 'Complete this field.', invalidEmail: 'Enter a valid email.', shortPassword: 'Use at least 8 characters.', mismatch: 'Passwords do not match.',
    unavailable: 'Could not load companies.', noCompanies: 'No companies are currently accepting requests.', retry: 'Retry', failed: 'Could not send your request.',
    requests: 'Registration requests', reviewIntro: 'Employee and client requests for the selected company.',
    pending: 'Awaiting approval', approved: 'Approved', rejected: 'Rejected', allTypes: 'All requests', empty: 'No requests in this section.', loading: 'Loading…',
    approve: 'Approve', reject: 'Reject', cancel: 'Cancel', position: 'Position', workshop: 'Workshop',
    applicantJob: 'Stated job title', employeeReview: 'Assign a position and a workshop if required.',
    clientReview: 'Approval will create a client account.', permissionsHint: 'Assign individual employee permissions in Employee permissions.',
    rejectHint: 'Rejecting this request will not create an account.', reviewFailed: 'Could not review this request.', listFailed: 'Could not load requests.', optionsFailed: 'Could not load positions and workshops.',
    approvalSaved: 'Registration approved.',
    notification: { sent: 'Approval email sent.', failed: 'The account is approved, but the email could not be sent.', unconfigured: 'The account is approved, but outgoing email is not configured on the server.', pending: 'The approval email has not been sent yet.', sending: 'Sending email…' },
    previous: 'Previous', next: 'Next', page: 'Page', rights: 'Permissions',
    roles: { admin: 'Administrator', manager: 'Manager', engineer: 'Engineer', laser: 'Laser cutting', bend: 'Bending', powder_catting: 'Powder coating' },
  },
}

export function registrationCopy(locale) {
  const selection = {
    hy: { allCompanies: 'Բոլոր ընկերությունները', reviewIntro: 'Աշխատակիցների և հաճախորդների հարցումները բոլոր այն ընկերություններից, որոնք կարող եք կառավարել։' },
    ru: { allCompanies: 'Все компании', reviewIntro: 'Заявки сотрудников и клиентов всех компаний, которыми вы можете управлять.' },
    en: { allCompanies: 'All companies', reviewIntro: 'Employee and client requests from all companies you can manage.' },
  }
  const language = String(locale || 'hy').split('-')[0]
  return { ...(copy[language] || copy.hy), ...(selection[language] || selection.hy) }
}
